### ISSUE TITLE
Commandline Interface

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#32]
**Description**
Add possibilty to call the program as a command via a terminal without the need of calling the java command beforehand

**Task**

- [x] #31
- [x] Find a dependency to package the program in a way that allows for cli start
- [x] Configure the dependency to suit the project
- [x] Test if it works

**Time required:**

- Optimistic: 30 min
- Pessimistic: 1h30
- Expected: 45 min
