### ISSUE TITLE
Define markers

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#53]
**Description**
We need to decide on markers to use in the layout file.

**Task**
- [x] Decide on marker for metadata
- [x] Decide on marker for file inclusion
- [x] Decide on marker for content inclusion

**Comment by MrDaves24** [comment]
I will do this task.
Estimated time : 30min
Expected time : 30min
Worst case : 1 hour
Output : Not any file, I will produce 3 regex usable to detect inputs.

**Comment by MrDaves24** [comment]
Meta-data (stuff from config file) :
Regex : "/\[\[ config.\S+ ]]/gi"
Example : [[ config.site_name ]]
Usage : In the config file, use the field name "site_name" to replace "[[ config.site_name ]]"
if the name is "site.name", it means to use the sub-field named "name" from the field "site".

**Comment by MrDaves24** [comment]
PR is in review
Time passed on the project : 30min with additional 15min for GitHub work !
Total time : 45min
PR merge will close this issue.
