### ISSUE TITLE
Implement layout file

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#56]
**Description**
We need to encapsulate all pages in a standard template file. For this issue, we only care about "decorating" all .md files with the content of the layout file.

**Task**
- [x] Decide where the files will reside
- [x] Implement layout file decoration
- [x] Create template layout file

Time required:

- Optimistic: 45 min
- Pessimistic: 1h30
- Expected: 1h00

**Comment by JoelMatias** [comment]
Les fichiers de template vont être stockés dans le dossier "template". il comprendra de fichier "layout.html"
