### ISSUE TITLE
Watch feature on `build` and `serve` commands

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#64]
**Description**
User stories request to add support for `build` and `serve` command to take a `--watch` flag that indicates to the program to automatically build / serve the application whenever a change occurs in the site's source files.

As an additional requirement, users want us to create diagrams detailing the abstraction that we will make on top of Java's WatchService API. 

**Task**
Add a list of optional tasks
- [ ] Create conception diagrams for abstraction
- [ ] Implement abstraction based on diagrams
- [ ] Add `--watch` flag to `serve`
- [ ] Add `--watch` flag to `build`

**Time estimates**
- Required: 4h
- Optimistic: 2h
- Pessimistic: 8h
