### ISSUE TITLE
Code quality overview

### ISSUE THREAD

**Issue by MaximGY** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#67]
**Description**
This is a composite issue, grouping all code quality related stories requested by users.
See task list below for full detail.

**Task**
Add a list of optional tasks
- [ ] Export Javadoc as HTML documents
- [ ] Use Jacoco to compute test code coverage
- [ ] Use LGTM or SonarQube to detect vulnerabilities / bugs
- [ ] use JHM to benchmark code performance

**Time estimates**
- Required: 5h
- Optimistic: 3h
- Pessimistic: 10h
