### ISSUE TITLE
Add comprehensive tests

### ISSUE THREAD

**Issue by Lothindir** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#82]
**Description**
We need to add tests to properly cover all code.

**Task**
- [x] Add `new` command tests
- [x] Add `clean` command tests
- [x] Add `build` command tests
- [x] Add `serve` command tests

**Time estimates**
- Required: 4h
- Optimistic: 3h
- Pessimistic: 8h

**Effective time taken:**
6h

**Comment by Lothindir** [comment]
Closed by #95
