### ISSUE TITLE
SiteBuilder Refactoring

### ISSUE THREAD

**Issue by MrDaves24** [dil-classroom/projet-marzullo_matias_monti_golay_perrenoud#91]
**Description**
Refactoring of "Build" command to separate the actual building from the use command

**Task**
Add a list of optional tasks
- [x] Create a class SiteBuilder
- [x] Transfer the code from Build to SiteBuilder
- [x] Use SiteBuilder in the Build command

**Time estimates**
- Realistic: 30min
- Optimistic: 15min
- Pessimistic: 1h

**Effective time taken: 45min**
